import{a as b,S as v,i as a}from"./assets/vendor-CrlV4O_2.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const P="https://pixabay.com/api/",q="50348687-5aaca11934b8ceb1ae22977b7",E=15;async function f(o,t=1){const n={key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:E,page:t};return(await b.get(P,{params:n})).data}const h=document.querySelector(".gallery"),g=document.querySelector(".loader"),m=document.querySelector(".load-more"),B=new v(".gallery a");function p(o){const t=o.map(({webformatURL:n,largeImageURL:i,tags:e,likes:r,views:s,comments:w,downloads:S})=>`
    <li>
      <a href="${i}">
        <img src="${n}" alt="${e}" />
      </a>
      <div>
        <p>👍 ${r}</p>
        <p>👁️ ${s}</p>
        <p>💬 ${w}</p>
        <p>⬇️ ${S}</p>
      </div>
    </li>
  `).join("");h.insertAdjacentHTML("beforeend",t),B.refresh()}function R(){h.innerHTML=""}function y(){g.classList.remove("hidden")}function L(){g.classList.add("hidden")}function $(){m.classList.remove("hidden")}function d(){m.classList.add("hidden")}const I=document.querySelector(".form"),M=document.querySelector(".load-more");let l=1,c="",u=0;d();I.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.currentTarget.elements["search-text"].value.trim(),!c){a.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}l=1,R(),d(),y();try{const t=await f(c,l);if(u=t.totalHits,t.hits.length===0){a.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(t.hits),u>t.hits.length&&$()}catch(t){console.error(t),a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L()}});M.addEventListener("click",async()=>{l+=1,y();try{const o=await f(c,l);p(o.hits),setTimeout(()=>{const n=document.querySelector(".gallery li");if(!n)return;const{height:i}=n.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})},100),document.querySelectorAll(".gallery li").length>=u&&(d(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(o){console.error(o),a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L()}});
//# sourceMappingURL=index.js.map
